# Shared design source list for terminal simulation.
# Testbenches are selected by the runner and are intentionally not listed here.
precision_lib/floating_point/fp_pkg.sv
precision_lib/bfloat16/bf16_pkg.sv
precision_lib/floating_point/mul_div/wallace32x32/aconfigure.sv
precision_lib/floating_point/mul_div/wallace32x32/add.sv
precision_lib/floating_point/mul_div/wallace32x32/cla.sv
precision_lib/floating_point/mul_div/wallace32x32/dadda.sv
precision_lib/floating_point/mul_div/wallace32x32/fa.sv
precision_lib/floating_point/mul_div/wallace32x32/ha.sv
precision_lib/floating_point/mul_div/wallace32x32/mul.sv
precision_lib/floating_point/mul_div/wallace32x32/mutex.sv
precision_lib/floating_point/mul_div/wallace32x32/wallace.sv
precision_lib/floating_point/lzc.sv
precision_lib/floating_point/fp_unpack.sv
precision_lib/floating_point/fp_pack.sv
precision_lib/floating_point/fp_add.sv
precision_lib/floating_point/fp_div.sv
precision_lib/floating_point/fp_mul.sv
precision_lib/floating_point/fp_to_int.sv
precision_lib/floating_point/int_to_fp.sv
precision_lib/floating_point/quake_fastinverse.sv
precision_lib/bfloat16/cast_fp32_to_bf16.sv
sync_fifos/fifo.sv
sync_fifos/axis_fifo_banked.sv
misc/delay.sv
misc/dpram.sv
rms_norm.sv
rms_norm_axi_wrapper.sv
