# Shared design source list for terminal simulation.
# Testbenches are selected by the runner and are intentionally not listed here.
rtl/precision_lib/floating_point/fp_pkg.sv
rtl/precision_lib/bfloat16/bf16_pkg.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/aconfigure.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/add.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/cla.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/dadda.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/fa.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/ha.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/mul.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/mutex.sv
rtl/precision_lib/floating_point/mul_div/wallace32x32/wallace.sv
rtl/precision_lib/floating_point/lzc.sv
rtl/precision_lib/floating_point/fp_unpack.sv
rtl/precision_lib/floating_point/fp_pack.sv
rtl/precision_lib/floating_point/fp_add.sv
rtl/precision_lib/floating_point/fp_div.sv
rtl/precision_lib/floating_point/fp_mul.sv
rtl/precision_lib/floating_point/fp_to_int.sv
rtl/precision_lib/floating_point/int_to_fp.sv
rtl/precision_lib/floating_point/quake_fastinverse.sv
rtl/precision_lib/bfloat16/cast_fp32_to_bf16.sv
rtl/sync_fifos/fifo.sv
rtl/sync_fifos/axis_fifo_banked.sv
misc/delay.sv
misc/dpram.sv
rtl/rms_norm.sv
rtl/rms_norm_axi_wrapper.sv
